<?php

namespace common\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "card_entry_user".
 *
 * @property int $id
 * @property string|null $username
 * @property string|null $full_name
 * @property string|null $phone_number
 * @property string|null $email
 * @property string|null $auth_key
 * @property string|null $password_hash
 * @property int|null $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class CardEntryUser extends \common\models\BaseModel implements IdentityInterface
{
    public $password_text;
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    const ROLE_USER = 10;
    const statusArray = [
        self::STATUS_DELETED=>"غير فعال",
        self::STATUS_ACTIVE=>"فعال",
    ];
    public  function getStatusText(){
        return self::statusArray[$this->status];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'card_entry_user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username'], 'required'],
            [['username', 'full_name', 'phone_number', 'email'], 'string'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['auth_key'], 'string', 'max' => 32],
            [['password_hash'], 'string', 'max' => 255],
            ["password_text", "required", "on" => ['create']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'رقم المستخدم'),
            'username' => Yii::t('app', 'اسم المستخدم'),
            'full_name' => Yii::t('app', 'الاسم'),
            'status' => Yii::t('app', 'الحالة'),
            'created_at' => Yii::t('app', 'تاريخ الانشاء'),
            'updated_at' => Yii::t('app', 'تاريخ التعديل'),
            'email' => Yii::t('app', 'الايميل'),
            'phone_number' => Yii::t('app', 'رقم التلفون'),
            'password_text' => Yii::t('app', 'كلمة السر'),
        ];
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\CardEntryUserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CardEntryUserQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord)
        {
            $this->generateAuthKey();
        }
        if(!empty($this->password_text))
        {
            $this->password_hash = Yii::$app->getSecurity()->generatePasswordHash($this->password_text);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
    /**
     * Finds user by username
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = bin2hex(Yii::$app->security->generateRandomKey(16));
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        $token = Yii::$app->jwt->getParser()->parse((string) $token);
        $token->getHeaders(); // Retrieves the token header
//        $token->getClaims(); // Retrieves the token claims
        $id = (string)$token->getClaim('uid');

        return static::findOne(['id' => $id, 'status' => User::STATUS_ACTIVE]);

    }
}
